package info.takebo.mybatis.plugin;

import java.util.List;

import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.JavaVisibility;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.TopLevelClass;

/**
 * add toString implementation in Model.
 */
public class ToStringPlugin extends PluginAdapter {

	@Override
	public boolean validate(List<String> warnings) {
		return true;
	}

	@Override
	public boolean modelBaseRecordClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {

		FullyQualifiedJavaType importedType = new FullyQualifiedJavaType("org.apache.commons.lang3.builder.ToStringBuilder");
		topLevelClass.addImportedType(importedType);

		Method method = new Method("toString");
		method.setVisibility(JavaVisibility.PUBLIC);
		method.setReturnType(new FullyQualifiedJavaType("String"));
		method.addBodyLine("return ToStringBuilder.reflectionToString(this);");

		method.addJavaDocLine(javaDoc());
		method.addAnnotation("@Override");

		topLevelClass.addMethod(method);

		return super.modelBaseRecordClassGenerated(topLevelClass, introspectedTable);
	}

	private String javaDoc() {
		return "/**\r\n" +
				"	 * This method was generated by MyBatis ToString Plugin.\r\n" +
				"	 * @mbggenerated\r\n" +
				"	 */";
	}
}